FROM node:20 AS builder
# Multi stage build (Build optimised front-end)
WORKDIR /app
COPY frontend .
RUN npm install
RUN npm build

FROM nginx:alpine
# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
RUN npm install --omit=dev
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
# this might not work yet, as I don't have an index.js