FROM node:20 AS builder
# Multi stage build (Build optimised front-end)
WORKDIR /app
COPY frontend .
RUN npm install
RUN npm run build

FROM nginx:alpine
# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80 
#ngin x listens on port 80
CMD ["nginx", "-g", "daemon off;"]
# this might not work yet, as I don't have an index.js